name: actividad3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Paso 3 - Construir imagen Docker
        run: docker build -t contenedor .

      - name: Paso 4 - Ejecutar main.py como módulo
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/static/csv":/pad_2025_1_2/static/csv \
            -v "${{ github.workspace }}/static/db":/pad_2025_1_2/static/db \
            contenedor
